
server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
#    url: jdbc:mysql://localhost:3306/student_analysis?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://106.54.3.97:3306/student_analysis?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: hello@
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapping/*Mapper.xml
  typeAliasesPackage: com.qztc.demo.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazyLoadingEnabled: true
    multipleResultSetsEnabled: true